# ##############################################################################
##  @file   .travis.yml
##  @brief  Configuration file for the Travis CI system.
##
##  @par References
##  - [https://docs.travis-ci.com/user/customizing-the-build]
##  - [https://docs.travis-ci.com/user/languages/c/]
# ##############################################################################

language: c

sudo: enabled

os: linux
dist: trusty



addons:
  sonarcloud:
    branches:
      - master
      - dev-issue-0003-mise_en_place_SonarCloud
    organization: "unice-etu-gom-github"

cache:
    directories:
        - '$HOME/.sonar/cache'



#before_install:



install:
    - sudo make install-dependencies



#before_script:



script:
    - make distclean
    # Wraps the compilation with the Build Wrapper to generate configuration (used
    # later by the SonarQube Scanner) into the "bw-output" folder
    - build-wrapper-linux-x86-64 --out-dir bw-output make
    #- make
    - sonar-scanner



#after_success:
#after_failure:



#before_deploy:
#deploy:
#after_deploy:



#after_script:

